server:
  port: 9080
  
security:
  oauth2:
    client:
      client-id: orderService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.imooc.com:9090/oauth/token_key
        
spring:
  application:
    name: orderApi
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080