server:
  port: 9060
  
security:
  oauth2:
    client:
      client-id: priceService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.imooc.com:9090/oauth/token_key
        
spring:
  application:
    name: priceApi
  cloud:
    sentinel:
      transport:
        port: 8717
        dashboard: localhost:8080